//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MergeWar.JavaServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SolrServerException", Namespace="http://service/")]
    [System.SerializableAttribute()]
    public partial class SolrServerException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IOException", Namespace="http://service/")]
    [System.SerializableAttribute()]
    public partial class IOException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service/", ConfigurationName="JavaServer.SCPInquireService")]
    public interface SCPInquireService {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MergeWar.JavaServer.SolrServerException), Action="", Name="SolrServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(MergeWar.JavaServer.IOException), Action="", Name="IOException")]
        MergeWar.JavaServer.addTerminalManageListResponse addTerminalManageList(MergeWar.JavaServer.addTerminalManageList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MergeWar.JavaServer.addTerminalManageListResponse> addTerminalManageListAsync(MergeWar.JavaServer.addTerminalManageList request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MergeWar.JavaServer.SolrServerException), Action="", Name="SolrServerException")]
        [System.ServiceModel.FaultContractAttribute(typeof(MergeWar.JavaServer.IOException), Action="", Name="IOException")]
        MergeWar.JavaServer.addNetLogListResponse addNetLogList(MergeWar.JavaServer.addNetLogList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MergeWar.JavaServer.addNetLogListResponse> addNetLogListAsync(MergeWar.JavaServer.addNetLogList request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MergeWar.JavaServer.queryTerminalManageListResponse queryTerminalManageList(MergeWar.JavaServer.queryTerminalManageList request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MergeWar.JavaServer.queryTerminalManageListResponse> queryTerminalManageListAsync(MergeWar.JavaServer.queryTerminalManageList request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addTerminalManageList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addTerminalManageList", Namespace="http://service/", Order=0)]
        public MergeWar.JavaServer.addTerminalManageListBody Body;
        
        public addTerminalManageList() {
        }
        
        public addTerminalManageList(MergeWar.JavaServer.addTerminalManageListBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addTerminalManageListBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public addTerminalManageListBody() {
        }
        
        public addTerminalManageListBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addTerminalManageListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addTerminalManageListResponse", Namespace="http://service/", Order=0)]
        public MergeWar.JavaServer.addTerminalManageListResponseBody Body;
        
        public addTerminalManageListResponse() {
        }
        
        public addTerminalManageListResponse(MergeWar.JavaServer.addTerminalManageListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addTerminalManageListResponseBody {
        
        public addTerminalManageListResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNetLogList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNetLogList", Namespace="http://service/", Order=0)]
        public MergeWar.JavaServer.addNetLogListBody Body;
        
        public addNetLogList() {
        }
        
        public addNetLogList(MergeWar.JavaServer.addNetLogListBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addNetLogListBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public addNetLogListBody() {
        }
        
        public addNetLogListBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addNetLogListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addNetLogListResponse", Namespace="http://service/", Order=0)]
        public MergeWar.JavaServer.addNetLogListResponseBody Body;
        
        public addNetLogListResponse() {
        }
        
        public addNetLogListResponse(MergeWar.JavaServer.addNetLogListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addNetLogListResponseBody {
        
        public addNetLogListResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryTerminalManageList {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryTerminalManageList", Namespace="http://service/", Order=0)]
        public MergeWar.JavaServer.queryTerminalManageListBody Body;
        
        public queryTerminalManageList() {
        }
        
        public queryTerminalManageList(MergeWar.JavaServer.queryTerminalManageListBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class queryTerminalManageListBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public queryTerminalManageListBody() {
        }
        
        public queryTerminalManageListBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryTerminalManageListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="queryTerminalManageListResponse", Namespace="http://service/", Order=0)]
        public MergeWar.JavaServer.queryTerminalManageListResponseBody Body;
        
        public queryTerminalManageListResponse() {
        }
        
        public queryTerminalManageListResponse(MergeWar.JavaServer.queryTerminalManageListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class queryTerminalManageListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public queryTerminalManageListResponseBody() {
        }
        
        public queryTerminalManageListResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SCPInquireServiceChannel : MergeWar.JavaServer.SCPInquireService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCPInquireServiceClient : System.ServiceModel.ClientBase<MergeWar.JavaServer.SCPInquireService>, MergeWar.JavaServer.SCPInquireService {
        
        public SCPInquireServiceClient() {
        }
        
        public SCPInquireServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCPInquireServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCPInquireServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCPInquireServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MergeWar.JavaServer.addTerminalManageListResponse MergeWar.JavaServer.SCPInquireService.addTerminalManageList(MergeWar.JavaServer.addTerminalManageList request) {
            return base.Channel.addTerminalManageList(request);
        }
        
        public void addTerminalManageList(string arg0) {
            MergeWar.JavaServer.addTerminalManageList inValue = new MergeWar.JavaServer.addTerminalManageList();
            inValue.Body = new MergeWar.JavaServer.addTerminalManageListBody();
            inValue.Body.arg0 = arg0;
            MergeWar.JavaServer.addTerminalManageListResponse retVal = ((MergeWar.JavaServer.SCPInquireService)(this)).addTerminalManageList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MergeWar.JavaServer.addTerminalManageListResponse> MergeWar.JavaServer.SCPInquireService.addTerminalManageListAsync(MergeWar.JavaServer.addTerminalManageList request) {
            return base.Channel.addTerminalManageListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MergeWar.JavaServer.addTerminalManageListResponse> addTerminalManageListAsync(string arg0) {
            MergeWar.JavaServer.addTerminalManageList inValue = new MergeWar.JavaServer.addTerminalManageList();
            inValue.Body = new MergeWar.JavaServer.addTerminalManageListBody();
            inValue.Body.arg0 = arg0;
            return ((MergeWar.JavaServer.SCPInquireService)(this)).addTerminalManageListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MergeWar.JavaServer.addNetLogListResponse MergeWar.JavaServer.SCPInquireService.addNetLogList(MergeWar.JavaServer.addNetLogList request) {
            return base.Channel.addNetLogList(request);
        }
        
        public void addNetLogList(string arg0) {
            MergeWar.JavaServer.addNetLogList inValue = new MergeWar.JavaServer.addNetLogList();
            inValue.Body = new MergeWar.JavaServer.addNetLogListBody();
            inValue.Body.arg0 = arg0;
            MergeWar.JavaServer.addNetLogListResponse retVal = ((MergeWar.JavaServer.SCPInquireService)(this)).addNetLogList(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MergeWar.JavaServer.addNetLogListResponse> MergeWar.JavaServer.SCPInquireService.addNetLogListAsync(MergeWar.JavaServer.addNetLogList request) {
            return base.Channel.addNetLogListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MergeWar.JavaServer.addNetLogListResponse> addNetLogListAsync(string arg0) {
            MergeWar.JavaServer.addNetLogList inValue = new MergeWar.JavaServer.addNetLogList();
            inValue.Body = new MergeWar.JavaServer.addNetLogListBody();
            inValue.Body.arg0 = arg0;
            return ((MergeWar.JavaServer.SCPInquireService)(this)).addNetLogListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MergeWar.JavaServer.queryTerminalManageListResponse MergeWar.JavaServer.SCPInquireService.queryTerminalManageList(MergeWar.JavaServer.queryTerminalManageList request) {
            return base.Channel.queryTerminalManageList(request);
        }
        
        public string queryTerminalManageList(string arg0) {
            MergeWar.JavaServer.queryTerminalManageList inValue = new MergeWar.JavaServer.queryTerminalManageList();
            inValue.Body = new MergeWar.JavaServer.queryTerminalManageListBody();
            inValue.Body.arg0 = arg0;
            MergeWar.JavaServer.queryTerminalManageListResponse retVal = ((MergeWar.JavaServer.SCPInquireService)(this)).queryTerminalManageList(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MergeWar.JavaServer.queryTerminalManageListResponse> MergeWar.JavaServer.SCPInquireService.queryTerminalManageListAsync(MergeWar.JavaServer.queryTerminalManageList request) {
            return base.Channel.queryTerminalManageListAsync(request);
        }
        
        public System.Threading.Tasks.Task<MergeWar.JavaServer.queryTerminalManageListResponse> queryTerminalManageListAsync(string arg0) {
            MergeWar.JavaServer.queryTerminalManageList inValue = new MergeWar.JavaServer.queryTerminalManageList();
            inValue.Body = new MergeWar.JavaServer.queryTerminalManageListBody();
            inValue.Body.arg0 = arg0;
            return ((MergeWar.JavaServer.SCPInquireService)(this)).queryTerminalManageListAsync(inValue);
        }
    }
}
